name: Python/Django CI

on:
  push:
    branches: [main] # main 브랜치에 push할 때
  pull_request:
    branches: [main] # main 브랜치로 PR 생성할 때

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 가져오기
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      # 2. Python 설정
      - name: Python 설정하기
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      # 3. 패키지 설치
      - name: 패키지 설치하기
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 테스트 실행
      - name: Django 테스트 실행하기
        run: |
          python manage.py test
