name: Python/Django CI

on:
  push:
    branches: [main] # main 브랜치에 push할 때
  pull_request:
    branches: [main]
    # main 브랜치로 PR 생성할 때

jobs:
  test: # 테스트 작업
    runs-on: ubuntu-latest
    steps:
      - name: 테스트 실행
        run: echo "테스트 실행"

  deploy: # 배포 작업
    needs: test # test 작업이 성공해야 실행
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기 # 1단계
        uses: actions/checkout@v2

      - name: 패키지 설치 # 2단계
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file # 3단계
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" > .env
          cat .env
